version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_cicd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=use-database

  use-api:
    build: .
    container_name: use-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb_cicd
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health"" ] # Or /actuator/health if using Spring Actuator
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  mongodb_data:
