name: Java CI with Maven
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        start_time=$(date +%s)
        mvn --batch-mode --update-snapshots verify | tee build_output.log
        end_time=$(date +%s)
        build_time=$((end_time - start_time))
        echo "BUILD_TIME_SECONDS=$build_time" >> build_output.log
      run: mvn --batch-mode --update-snapshots verify
    - name: Upload build result use-assembly
      run: mkdir staging && cp use-assembly/target/*.zip staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - uses: actions/upload-artifact@v4
      with: 
        name: build-log
        path: build_output.log
    - uses: actions/upload-artifact@v4
      with:
        name: failure-reports
        path: |
          docs/archunit-results/cycles-current-failure-report.txt
          docs/archunit-results/layers-current-failure-report.txt
        
    - name: Upload build result use-api
      run: mkdir testphase && cp use-api/target/use-api-7.1.1.jar testphase
    - uses: actions/upload-artifact@v4
      with:
        name: constructed_use-api
        path: testphase
        

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
     #Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3 # dont need to checkout if I put the postman collection into the artifact

    # Set up JDK
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        #cache: maven

    - name: Download Artifact use-api
      uses: actions/download-artifact@v4
      with:
        name: constructed_use-api
      

      
    # Start Spring Boot
    - name: Start Spring Boot
      run: java -Dspring.profiles.active=test -jar use-api-7.1.1.jar &
      env:
        SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

    # Wait for Spring Boot to start
    - name: Wait for Spring Boot
      run: |
        for i in {1..5}; do
          curl --fail http://localhost:8080/actuator/health && break || sleep 10;
        done

    # Run Postman Tests with Newman
    - name: Run Postman tests
      run: |
        npm install -g newman
        newman run use-api/src/it/java/org.tzi.use/postman_collection/use-webapi.postman_collection.json


    # Cleanup
    - name: Stop Spring Boot
      run: pkill -f 'java -Dspring.profiles.active=test'  
